### ISSUE TITLE
MLIR support

### ISSUE THREAD

**Issue by victorygogogo** [lutzroeder/netron#1043] opened 2023-02-06 05:47 UTC
how to support mlir file about netron?

**Comment by lutzroeder** [comment] 2023-02-06 05:59
@victorygogogo can you provide some context. Are you trying to create a pull request to to add MLIR support? Can you share a sample model file, how it was created and how it is used.

**Comment by victorygogogo** [comment] 2023-02-06 09:36
mlir file content as flow:
module {
  func.func @test_onnx_conv_simple_pattern(%arg0: tensor<5x3x32x32xf32>, %arg1: tensor<?x3x2x2xf32>) -> tensor<5x?x31x31xf32> {
    %0 = "onnx.NoValue"() {value} : () -> none
    %1 = "onnx.Conv"(%arg0, %arg1, %0) {auto_pad = "NOTSET", kernel_shape = [2, 2], pads = [0, 0, 0, 0]} : (tensor<5x3x32x32xf32>, tensor<?x3x2x2xf32>, none) -> tensor<5x?x31x31xf32>
    return %1 : tensor<5x?x31x31xf32>
  }
}
I am trying to find some tool to support mlir file to visualize as netron, if netron support is best.

**Comment by lutzroeder** [comment] 2023-02-07 06:55
@victorygogogo can you implement MLIR support and submit a pull request. Both an JavaScript parser and code to translate into objects for visualization can be added to [mlir.js](https://github.com/lutzroeder/netron/blob/main/source/mlir.js).

**Comment by lutzroeder** [comment] 2023-02-07 06:56
Duplicate of #1044

**Closed by lutzroeder** 2023-02-07 06:56 UTC
Labels: feature
