### ISSUE TITLE
Export model weights file

### ISSUE THREAD

**Issue by wl3b10s** [lutzroeder/netron#450] opened 2020-03-25 04:17 UTC
hi
i had a question on 

how to automatically save model's weights of each layer to  file through call netron from python? 
currently i only know the method to save weights of layer through webpage.

thank you.

**Comment by lutzroeder** [comment] 2020-03-25 05:06
This is not supported and currently not a priority. To export all weights load the file with the framework it was created with and use the weights export or one of the many converters out there.

**Comment by lutzroeder** [comment] 2020-03-25 05:06
Duplicate of #300

**Closed** 2021-12-27 14:47 UTC
Labels: feature
