### ISSUE TITLE
Backspace stopped working in netron 7.3.1

### ISSUE THREAD

**Issue by xwin** [lutzroeder/netron#1199] opened 2023-11-29 15:28 UTC
- Netron app and version: 
Netron desktop app v7.3.1
- OS and browser version: 
Windows 10 build 19045, Chrome 119.0.6045.160

Steps to Reproduce:
1. Open a model in netron, works with any model
2. Press Ctrl-F to open Find dialog
3. Type something in
4. Now try to delete it using backspace, nothing will happen
5. Ctrl+backspace however works, it will clear the entry field.
6. The arrow keys and delete also work.

Expected result - backspace deletes last character. This worked before and became broken in latest version.

**Comment by lutzroeder** [comment] 2023-11-29 17:23
Duplicate of #1195

**Closed by lutzroeder** 2023-11-29 17:23 UTC
Labels: bug
