### ISSUE TITLE
Netron doesn't show data shapes for TF models

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#399] opened 2019-12-20 06:56 UTC
The same model in TF format is shown without shapes (https://people.freebsd.org/~yuri/android_graph-yolo.pb):

![image](https://user-images.githubusercontent.com/271906/71235801-0fa1b380-22b2-11ea-8d44-df91e36089ae.png)

and in TF Lite formatted model is shown with shapes (https://people.freebsd.org/~yuri/android_graph-yolo.tflite):

![image](https://user-images.githubusercontent.com/271906/71235891-51caf500-22b2-11ea-8b9a-5642e0f6a5bf.png)

The .tflite file was obtained by converting the original .pb model, so they represent exactly the same model.

In a NN model all intermediate data has fixed formats, so .pb should have shapes shown too.

**Comment by lutzroeder** [comment] 2019-12-20 07:19
TensorFlow Lite infers the shapes during conversion and includes the resulting file. TensorFlow infers them at runtime.

**Comment by lutzroeder** [comment] 2019-12-20 07:19
Duplicate of #71

**Closed by lutzroeder** 2019-12-20 07:19 UTC
