### ISSUE TITLE
Cannot open large models

### ISSUE THREAD

**Issue by zengzhi2015** [lutzroeder/netron#323] opened 2019-08-26 04:27 UTC
It seems that the app cannot open large models like DeepLab. You could try this model. (I can open this using TensorBoard.)

[graph.zip](https://github.com/lutzroeder/netron/files/3539403/graph.zip)

**Comment by lutzroeder** [comment] 2019-08-26 08:45
Duplicate of #68

**Closed by lutzroeder** 2019-08-26 08:45 UTC
Labels: duplicate

**Comment by lutzroeder** [comment] 2024-01-28 00:02
[0323.pbtxt.zip](https://github.com/lutzroeder/netron/files/14074343/0323.pbtxt.zip)
