### ISSUE TITLE
Ubuntu: Export as PNG or SVG doesn't work

### ISSUE THREAD

**Issue by shawnmasters** [lutzroeder/netron#985] opened 2022-10-05 13:39 UTC
- Netron appimage - 6.0.8 for Linux
- Ubuntu 22.04 Intel i7

I can load a model (only used onnx so far) and browse through it just fine.  When I select the export option I get a file dialog.  It has PNG and SVG as save options.  Neither of those options actually save a file to my disk.  The output on stdout and stderr don't show any indictations of an attempt to save a file or a failure while trying.  I do have other output from the program on the command line though.  Indications of version and checking for upgrades and an error pasted below that occurs multiple times.

[1610245:1005/093152.118004:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1610245:1005/093159.037071:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[1610245:1005/093159.039338:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

The rest of the application appears to work correctly.

**Comment by shawnmasters** [comment] 2022-10-05 13:42
Update.  If I manually add the ".png" extension it can write the file.

**Comment by lutzroeder** [comment] 2022-10-05 16:30
Duplicate of #861

**Closed by lutzroeder** 2022-10-05 16:30 UTC
Labels: bug
