### ISSUE TITLE
Unable to open SDXL Turbo unet model in Netron

### ISSUE THREAD

**Issue by kartikpodugu** [lutzroeder/netron#1265] opened 2024-04-20 17:57 UTC
Netron app and version:  Desktop app  7.6.1 version
OS Version : Windows 11

Steps to Reproduce:

1.Download onnx model and external data from here https://huggingface.co/stabilityai/sdxl-turbo/tree/main/unet
2.Try to open the model using Netron app

Netron doesn't throw any error, and it doesn't open the model also.

**Comment by lutzroeder** [comment] 2024-04-20 19:02
Duplicate of #1214

**Closed by lutzroeder** 2024-04-20 19:02 UTC
Labels: bug
