### ISSUE TITLE
Core ML: mlmodel not showing shape of layers

### ISSUE THREAD

**Issue by yousifa** [lutzroeder/netron#987] opened 2022-10-06 03:36 UTC
- Netron app and version: 6.0.5
- OS and browser version: MacOS 12.5.1

Steps to Reproduce:

1. Open Neural Network type mlmodel
2. No shapes present for any of the layers

Note: shapes appear normally for mlpackage coreml models using "mlprogram" type of neural network

Please attach or link model files to reproduce the issue if necessary.
[model.mlmodel.zip](https://github.com/lutzroeder/netron/files/9720945/model.mlmodel.zip)

An example model is attached.

**Comment by lutzroeder** [comment] 2022-10-07 02:29
Non-mlprogram models often do not store tensor shapes in the model file. The inputs of the activation layers in the attached model include shapes, the other layers do not.

**Comment by lutzroeder** [comment] 2022-10-07 03:02
Duplicate of #71

**Closed by lutzroeder** 2022-10-07 03:02 UTC
Labels: bug
