### ISSUE TITLE
Why the caffe and onnx model weight type is float32 but it looks like a double type

### ISSUE THREAD

**Issue by blacklong28** [lutzroeder/netron#807] opened 2021-09-14 02:19 UTC
![image](https://user-images.githubusercontent.com/13930040/133183806-22c8fd52-ab7b-4c04-a7fe-37b9109e40ec.png)
I am very puzzled。
I didn't read the code, can anyone tell me?

**Comment by lutzroeder** [comment] 2021-09-14 03:09
Duplicate of #478

**Closed by lutzroeder** 2021-09-14 03:09 UTC
Labels: bug
