### ISSUE TITLE
How to export all weight with netron

### ISSUE THREAD

**Issue by HappyAIWalker** [lutzroeder/netron#819] opened 2021-10-02 06:51 UTC

**Comment by HappyAIWalker** [comment] 2021-10-02 06:52
I can open a pdparams with netron, but how can I export the weight? If is it possible export all the weight with several line code by netron. Hoping for your reply.

**Comment by lutzroeder** [comment] 2021-10-02 15:21
Duplicate of #450

**Closed by lutzroeder** 2021-10-02 15:21 UTC
Labels: feature
