### ISSUE TITLE
Weights export 

### ISSUE THREAD

**Issue by holoLens8** [lutzroeder/netron#489] opened 2020-05-11 12:58 UTC
Is there a way to export weights as int8 instead of float32.
I tried to visualize a quantized network, but I always get float32 weights.

**Comment by lutzroeder** [comment] 2020-05-11 14:57
Can you share the model file?

**Comment by lutzroeder** [comment] 2020-05-11 15:07
Duplicate of #300

**Closed** 2020-05-11 15:07 UTC

**Comment by holoLens8** [comment] 2020-05-11 16:03
Here is the file.
Thanks


Nermine

Le lun. 11 mai 2020 à 16:57, Lutz Roeder <notifications@github.com> a
écrit :

**Comment by lutzroeder** [comment] 2020-05-11 20:09
ONNX forums might be a better place to ask how quantization works in ONNX?
