### ISSUE TITLE
ONNX: Subgraph support

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [lutzroeder/netron#535] opened 2020-07-14 15:27 UTC
TF models show a "subgraph" dropdown for viewing subgraphs, but ONNX models do not.  The ability to view ONNX subgraphs would be extremely helpful to me.

**Comment by lutzroeder** [comment] 2020-07-14 18:20
Can you share a sample file?

**Comment by TomWildenhain-Microsoft** [comment] 2020-07-14 18:32
Sure.  This graph has a subgraph for the then and else branches.  Thanks!  [https://github.com/TomWildenhain-Microsoft/onnx-example-with-subgraphs/blob/master/k1.onnx](https://github.com/TomWildenhain-Microsoft/onnx-example-with-subgraphs/blob/master/k1.onnx)

**Comment by lutzroeder** [comment] 2020-08-27 15:34
Duplicate of #168

**Closed by lutzroeder** 2020-08-27 15:34 UTC
Labels: feature
