### ISSUE TITLE
float32 data displayed as float64

### ISSUE THREAD

**Issue by qqice** [lutzroeder/netron#1176] opened 2023-10-26 11:59 UTC
- Netron app and version: 7.2.6 Desktop app
- OS and browser version: Windows 11 Enterprise 22635.2486

Steps to Reproduce:
1. Open the .npy data"model_input1.npy", in which numbers are stored with type `numpy.float32`.
![image](https://github.com/lutzroeder/netron/assets/39629131/647b9bbf-c055-404d-a68e-781ca356d5ad)
2. Run the test python code below, which will display the original data and the data after being converted to float64 using `float()`.
```python
import numpy as np
input_1=np.load("model_input1.npy")
print("original input: ")
for i in range(10):
    print(input_1[0,0,i]) # this will print the first 10 elements of the original input
print("original input as float64: ")
for i in range(10):
    print(float(input_1[0,0,i])) # this will print the first 10 elements of the original input as float64
```
![image](https://github.com/lutzroeder/netron/assets/39629131/d62b17ed-0d43-42f3-88a2-bb68bf1a1afa)

It seems that Netron displays float32 data as float64.
The .npy file is attached below.
[model_input1.zip](https://github.com/lutzroeder/netron/files/13177029/model_input1.zip)

**Comment by lutzroeder** [comment] 2023-10-26 15:15
Duplicate of #478

**Closed by lutzroeder** 2023-10-26 15:15 UTC
Labels: bug

**Comment by lutzroeder** [comment] 2023-10-26 15:17
Duplicate of #478

**Comment by lutzroeder** [comment] 2023-10-27 01:16
@qqice see #478. This is a specific formatting implementation in NumPy. Can you investigate and propose a solution.

```py
import numpy as np
x = np.float32(7.3864746)
print(x)
# 7.3864746
print(x.item())
# 7.386474609375
```
