### ISSUE TITLE
Automating export to image

### ISSUE THREAD

**Issue by clstaudt** [lutzroeder/netron#400] opened 2019-12-20 13:27 UTC
I wonder if it is possible to use the `netron` Python module to automate the export of a model visualization to an image.  Great as the Netron desktop app is, I would like to skip the manual step of exporting the model to a file, opening it, exporting an image and including it in my Jupyter Notebooks.

**Comment by lutzroeder** [comment] 2019-12-21 00:07
Duplicate of #162

**Closed by lutzroeder** 2019-12-21 00:07 UTC
Labels: help wanted

**Comment by dnola** [comment] 2020-01-13 20:53
Hello, 

How is this a duplicate of the other issue? I don't believe the comments in the other issue address what is being requested here - #162 provides no programmatic means of automating image export - the solutions there all require user intervention - be it to upload a model, or click to save an image.

Thus, there is no outstanding means of automating image export. Should this be reopened?

**Comment by clstaudt** [comment] 2020-01-13 21:07
Thank you @dnola. In the "duplicate" issue I couldn't find something relevant to my question, so closing this seems like a mistake to me.

**Comment by dnola** [comment] 2020-01-13 21:18
Agreed - and this is so often requested (and subsequently closed without explanation), that I feel it deserves a little more attention than it is getting. At the very least maybe something like a documentation change to describe how to do this - as if this behavior is already in Netron, it certainly doesn't appear to be documented well enough to prevent the issue coming back up repeatedly.

Though my sense is that this actually would be new behavior - at the very least making an endpoint to upload an arbitrary model, eg via POST or something (?url= I believe is gonna require the file to be actively hosted somewhere), and something client side to allow automated saving without needing to menu into the export options.

**Comment by clstaudt** [comment] 2020-01-13 21:21
Naive question: Netron is a Python module, why not expose a function that takes a model and exports an image?

**Comment by dnola** [comment] 2020-01-13 21:22
The issue, from my understanding, is that Netron operates specifically as an interactive visualization tool - the server doesn't generate the 'image', the client does. So it does need to be a little more complicated than that unfortunately!
