### ISSUE TITLE
Tensorflow Lite, Netron 3.7.9: TypeError "node.operator.split" is not a function

### ISSUE THREAD

**Issue by mendi80** [lutzroeder/netron#417] opened 2020-01-21 01:15 UTC
This error appear only in tflite file and netron 3.7.9
Error does not appear in same network saved in h5 keras file.
Error does not appear in netron 3.7.8

**Comment by lutzroeder** [comment] 2020-01-21 01:16
Can you share the model file?

**Comment by lutzroeder** [comment] 2020-01-21 01:16
Duplicate of #416

**Closed by lutzroeder** 2020-01-21 01:16 UTC

**Comment by mendi80** [comment] 2020-01-21 02:30
model uploaded

**Comment by mendi80** [comment] 2020-01-21 02:33
BTW:
1) Is there any way to see number of parameters (per layer, total) in keras models?
2) Why is that in tflite file i can see the activation shape, but in keras h5 file i cant?

**Comment by lutzroeder** [comment] 2020-01-21 05:34
> Is there any way to see number of parameters (per layer, total) in keras models?

Can you provide some more specifics?

> Why is that in tflite file i can see the activation shape, but in keras h5 file i can't?

The shapes are computed during conversion and stored in `.tflite` files. They are not stored in Keras files and have to be inferred. See #71.
