### ISSUE TITLE
pytorch have some problem

### ISSUE THREAD

**Issue by zjp99** [lutzroeder/netron#359] opened 2019-10-29 07:49 UTC
My model load shows 100 modules with no wires.
.pth   in https://github.com/xingyizhou/CenterNet
Use CenterNet  ----> ctdet_coco_dla_2x.pth   for detection

**Comment by lutzroeder** [comment] 2019-10-29 10:53
Duplicate of #133

**Closed by lutzroeder** 2019-10-29 10:53 UTC
Labels: duplicate

**Comment by lutzroeder** [comment] 2022-09-24 21:16
Duplicate of #720

**Comment by lutzroeder** [comment] 2022-09-24 21:16
Duplicate of #720
