### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by Ki6an** [lutzroeder/netron#680] opened 2021-02-08 10:31 UTC
- Netron app and version:  4.7.6 (pip)
- OS and browser version: Colab

Steps to Reproduce:
I've installed Netron through pip in Colab notebook 

when I run the following code to visualize the model 
```
import netron
netron.start('/content/onnx-encoder.onnx')
```
I'm getting this error :

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-28df5e7b8b28> in <module>()
      1 import netron
----> 2 netron.start('/content/onnx-encoder.onnx')

5 frames
/usr/lib/python3.6/socketserver.py in server_bind(self)
    468         if self.allow_reuse_address:
    469             self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
--> 470         self.socket.bind(self.server_address)
    471         self.server_address = self.socket.getsockname()
    472 

OSError: [Errno 98] Address already in use
```

how can I resolve this issue ?

**Comment by Ki6an** [comment] 2021-02-13 10:57
if anyone is struggling with the same issue follow this [notebook ](https://colab.research.google.com/gist/blois/227d21df87fe8a390c2a23a93b3726f0/netron.ipynb)

**Comment by lutzroeder** [comment] 2021-02-14 05:05
```
!wget https://storage.googleapis.com/download.tensorflow.org/models/tflite/smartreply_1.0_2017_11_01.zip
!unzip smartreply_1.0_2017_11_01.zip
!pip install -q netron
```
```python
import netron
from google.colab import output
_, port = netron.start('smartreply.tflite')
output.serve_kernel_port_as_iframe(port, height='800')
```

**Comment by lutzroeder** [comment] 2021-02-14 17:10
Duplicate of #219

**Closed by lutzroeder** 2021-02-14 17:10 UTC
Labels: bug
