### ISSUE TITLE
'url' query parameter in Netron

### ISSUE THREAD

**Issue by GiorgiGagnidze** [lutzroeder/netron#811] opened 2021-09-20 13:57 UTC
How is the url parameter supposed to be used?

I am trying to use Netron the way it is described in #302 

I tried to pass local model path to url parameter but it failed. 

Is this valid use of this feature ? - `https://netron.app?url=/path/to/local/file/model.onnx`

If not, can you give me a valid example of how to use this parameter? Link in the attached issue also fails.

**Comment by lutzroeder** [comment] 2021-09-20 18:12
The app is running in the browser and does not have access to the local file system.

The [README](https://github.com/lutzroeder/netron/blob/main/README.md) contains some URL examples which requires [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) to be configured on the remote server .

**Comment by lutzroeder** [comment] 2021-09-20 18:13
Duplicate of #697

**Closed by lutzroeder** 2021-09-20 18:12 UTC
Labels: bug

**Comment by cbodenst** [comment] 2021-09-22 15:19
Hi just one more question. If the url inludes query parameters itself this seems not to work. Is there any workaround to this?

Example: https://my.server.com/models.h5?model_id=a&version=15

**Comment by lutzroeder** [comment] 2021-09-22 16:52
`https://netron.app?identifier=models.h5&url=https%3A%2F%2Fmy.server.com%2Fmodels.h5%3Fmodel_id%3Da%26version%3D15`

**Comment by cbodenst** [comment] 2021-09-23 17:51
Thank you. This works!

**Comment by tpoisonooo** [comment] 2022-12-29 09:54
Ah it works !

After CORS configured
