### ISSUE TITLE
Can you provide a functioin on export parameter of the model?

### ISSUE THREAD

**Issue by GuideWsp** [lutzroeder/netron#527] opened 2020-06-23 01:39 UTC
Netron is a very good tools, I nearly use it everyday. Recently, I want to export the model parameters of t7, so if you can provide a function to export the parameters of the model to npy or mat?

**Comment by lutzroeder** [comment] 2020-06-23 03:44
Duplicate of #300

**Closed by lutzroeder** 2020-06-23 03:44 UTC

**Comment by GuideWsp** [comment] 2020-06-23 03:58
oh, I know how to it, thank you very much
