### ISSUE TITLE
How to build same model using drag and drop feature in UI

### ISSUE THREAD

**Issue by akhilesh2310** [lutzroeder/netron#510] opened 2020-06-05 09:59 UTC
Hi

I would like to know how can I build same graph using drag and drop.
Basically this library gives the preview of existing model and My requirement is to create new model from scratch using drag and drop layers in UI. Any guidance would help. Thank you.

**Comment by lutzroeder** [comment] 2020-06-05 20:18
Duplicate of #275

**Closed by lutzroeder** 2020-06-05 20:18 UTC
