### ISSUE TITLE
Can it hightlight the selected line ?

### ISSUE THREAD

**Issue by wwdok** [lutzroeder/netron#899] opened 2022-04-08 02:44 UTC
I met such a model as below, I can not figure out the line connect to which node, if it can highlight the selected line, then we can konw what two nodes are connected, by the way, if it could highlight two connected nodes as well, it seems to be better.
![image](https://user-images.githubusercontent.com/43233772/162352012-8bdf8f0e-4721-40b9-83bb-14c8fe212bd9.png)
The model I open is:
[face_landmark_with_attention.zip](https://github.com/lutzroeder/netron/files/8448094/face_landmark_with_attention.zip)

**Comment by lutzroeder** [comment] 2022-04-08 02:48
Duplicate of #181 and #610

**Closed by lutzroeder** 2022-04-08 02:48 UTC
Labels: feature
