### ISSUE TITLE
MindSpore support

### ISSUE THREAD

**Issue by Harry06145** [lutzroeder/netron#1403] opened 2024-11-28 02:41 UTC
I would like to express my appreciation for the amazing work you’ve done on Netron. It’s truly a powerful and convenient tool for visualizing neural networks, and I’ve had a great experience using it with PyTorch. The interface is intuitive, and it helps me understand and debug my models much more effectively.

That being said, I’ve recently started learning and working with MindSpore, and I noticed that Netron doesn’t currently support this framework. As MindSpore continues to gain traction, it would be fantastic to see support for it in future versions of Netron. I believe adding support for more deep learning frameworks would make Netron even more versatile and beneficial to a wider range of users.

I understand that supporting additional frameworks takes time and effort, but I just wanted to share this feedback in the hope that it might be considered for future updates. Thank you again for developing such a great tool, and I look forward to seeing how it evolves!

**Comment by lutzroeder** [comment] 2024-11-28 03:45
@Harry06145 can you clarify what which support this is referring as MindSpore supports many formats.

**Comment by lutzroeder** [comment] 2024-11-28 03:45
Duplicate of #600

**Closed by lutzroeder** 2024-11-28 03:45 UTC
Labels: feature
