### ISSUE TITLE
Unsupported 'torch.ne' expression type

### ISSUE THREAD

**Issue by skyline75489** [lutzroeder/netron#915] opened 2022-05-25 04:30 UTC
- Netron app and version:  5.8.1 Desktop app
- OS and browser version:  Windows 11 10.0.22621.1

Steps to Reproduce:

1. Opens torchtext models XLMR_BASE_ENCODER and ROBERTA_BASE_ENCODER
2.

Please attach or link model files to reproduce the issue if necessary.

I don't know how I can attach the model file, but you can easily get the model using:

```python
import sys
import os
import traceback
import torch
import torchtext
import torch.utils.bundled_inputs
import torch.utils.mobile_optimizer
import torch.backends._nnapi.prepare
from torchtext.functional import to_tensor
from pathlib import Path

def export_model(model, quant=False):
    cpu_model = torch.utils.mobile_optimizer.optimize_for_mobile(torch.jit.script(model))

    input_float = torch.zeros(2, 6, dtype=torch.int64)
    input_tensor = input_float

    #with torch.no_grad():
    #    traced = torch.jit.trace(model, input_tensor)
    #nnapi_model = torch.backends._nnapi.prepare.convert_model_to_nnapi(traced, input_tensor)


    output_dir_path = Path('.')

    cpu_model = torch.utils.bundled_inputs.bundle_inputs(
        cpu_model, [(input_tensor, None)]
    )

    cpu_model._save_for_lite_interpreter(os.path.join(output_dir_path, ("{}_quant-{}-cpu.pt".format('XLMR_BASE_ENCODER', "core" if quant else "none"))))


xlmr_base = torchtext.models.XLMR_BASE_ENCODER
model = xlmr_base.get_model()
transform = xlmr_base.transform()
input_batch = ["Hello world", "How are you!"]
model_input = to_tensor(transform(input_batch), padding_value=1)

model.eval()

quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.qint8
)
#print(quantized_model)

export_model(model)
export_model(quantized_model, True)
```

**Comment by lutzroeder** [comment] 2022-05-25 12:57
Duplicate of https://github.com/pytorch/pytorch/issues/48525

**Closed by lutzroeder** 2022-05-25 12:57 UTC
Labels: bug
