### ISSUE TITLE
Force automatic update

### ISSUE THREAD

**Issue by wang-kangkang** [lutzroeder/netron#829] opened 2021-10-14 11:56 UTC
Why set up forced automatic updates???

**Comment by lutzroeder** [comment] 2021-10-14 18:45
Duplicate of #243

**Closed by lutzroeder** 2021-10-14 18:45 UTC
Labels: feature

**Comment by oxygen-dioxide** [comment] 2024-05-20 08:29
> Why set up forced automatic updates???

You can Install netron with pip: `pip install netron` which won't update automatically
