### ISSUE TITLE
Only show first layer of my pytorch .pth model

### ISSUE THREAD

**Issue by jiang-yuan** [lutzroeder/netron#566] opened 2020-08-01 12:38 UTC
I want to check my full model include all the sub modules insider my model.
But neutron only shows the first layer of my model, it is meaning less for me because it does not provide the informaition I need.
Here is my model.
[critic.zip](https://github.com/lutzroeder/netron/files/5010360/critic.zip)

**Comment by lutzroeder** [comment] 2020-08-01 12:41
Duplicate of #338

**Closed by lutzroeder** 2020-08-01 12:41 UTC
Labels: feature
