### ISSUE TITLE
TorchScript: Too many dimensions for input?

### ISSUE THREAD

**Issue by TechInterMezzo** [lutzroeder/netron#1142] opened 2023-08-25 05:31 UTC
- Netron app and version: 7.1.4 Desktop app
- OS and browser version: Windows 10

Steps to Reproduce:

1. Download https://github.com/snakers4/silero-vad/blob/master/files/silero_vad.jit
2. Rename from silero_vad.jit to silero_vad.pt
3. Open silero_vad.pt with Netron

**Comment by lutzroeder** [comment] 2023-08-25 13:02
[silero_vad.zip](https://github.com/lutzroeder/netron/files/12439374/silero_vad.zip)

**Comment by lutzroeder** [comment] 2023-08-26 22:11
Duplicate of #1061

**Closed by lutzroeder** 2023-08-26 22:11 UTC
Labels: bug
