### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jnorwood** [lutzroeder/netron#204] opened 2018-12-13 20:23 UTC
I didn't find a view item for summaries in the menu, so I'm assuming it isn't a current feature.
I'm looking for per layer and full model totals of resources and operations.
This netscope viewer has per layer info (scroll to bottom), but no model summary.
https://dgschwend.github.io/netscope/#/preset/resnet-50
Is any feature like that under development?  If not, please add it to a wish list.

**Comment by pawan9** [comment] 2019-04-01 16:39
Can you please add MACCs, FLOPS and Memory access info per layer and for full model.

**Comment by lutzroeder** [comment] 2021-03-21 00:59
@headdab

**Comment by Fannettembrown** [comment] 2022-03-14 00:24
Called a Sequential model value....

**Comment by widiba03304** [comment] 2022-09-06 09:27
Is there any plan to add this feature? If not, I am very interested in implementing this.

**Comment by lutzroeder** [comment] 2024-03-06 02:25
Duplicate of #1240 and #1241

**Closed by lutzroeder** 2024-03-06 02:25 UTC
Labels: feature, help wanted
