### ISSUE TITLE
stuck when viewing bert

### ISSUE THREAD

**Issue by tesla-cat** [lutzroeder/netron#279] opened 2019-05-31 18:46 UTC
i am using WIN10 AMD ryzen 2500 CPU, when i try to view BERT (https://github.com/google-research/bert), the program stucks. I wonder this is a problem with netron or my device?

**Comment by lutzroeder** [comment] 2019-05-31 18:51
Can you share the model file or a link to the file?

**Comment by lutzroeder** [comment] 2019-05-31 19:20
Duplicate of #68

**Closed by lutzroeder** 2019-05-31 19:20 UTC
Labels: duplicate, question
