### ISSUE TITLE
openvino weights not shown

### ISSUE THREAD

**Issue by eladeyal-intel** [lutzroeder/netron#407] opened 2020-01-07 23:08 UTC
Open the xml+bin file pair from https://github.com/lutzroeder/netron/blob/master/test/models.json#L3565

https://download.01.org/openvinotoolkit/2018_R4/open_model_zoo/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
https://download.01.org/openvinotoolkit/2018_R4/open_model_zoo/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.bin

right click the first convultion and look for the blobs. The `weights` fails with "tensor shape undefined" while the `biases` correctly show 16 float16s (I thought it would derive this from size=32). Likewise the biases size 864 can be interpreted as 432 float16s

```xml
<layer id="2" name="68" precision="FP16" type="Convolution">
    <data dilations="1,1" group="1" kernel="3,3" output="16" pads_begin="1,1" pads_end="1,1" strides="1,1"/>
    <input>
		<port id="0">
			<dim>1</dim>
			<dim>3</dim>
			<dim>48</dim>
			<dim>48</dim>
		</port>
    </input>
    <output>
		<port id="3">
			<dim>1</dim>
			<dim>16</dim>
			<dim>48</dim>
			<dim>48</dim>
		</port>
    </output>
    <blobs>
		<weights offset="12" size="864"/>
		<biases offset="876" size="32"/>
    </blobs>
</layer>
```

![image](https://user-images.githubusercontent.com/20379005/71936891-6284d180-31b3-11ea-9321-8ad255f900b4.png)

**Comment by lutzroeder** [comment] 2020-01-08 03:51
Duplicate of #307

**Closed by lutzroeder** 2020-01-08 03:51 UTC
Labels: help wanted
