### ISSUE TITLE
Jupyter IFrame support

### ISSUE THREAD

**Issue by radiantone** [lutzroeder/netron#159] opened 2018-10-08 18:32 UTC
Hi,
 I have a keras model (tensorflow backend). Can I use this to visualize it in jupyter?

**Comment by lutzroeder** [comment] 2018-10-08 18:48
See #96. Feedback is welcome.

**Comment by radiantone** [comment] 2018-10-08 18:52
I dont think that #96 ticket provides all the details needed in this ticket.

How to export the keras model to browse?
What is the server port of the netron server?
I'm not running it locally.

Just need a few concrete details here. Thanks

**Comment by lutzroeder** [comment] 2018-10-08 19:11
```
keras_model.save('test.h5')
!pip install netron
import netron
netron.browse('test.h5', port=8081)
```

**Comment by radiantone** [comment] 2018-10-09 12:14
Thanks!

**Comment by sjain-stanford** [comment] 2021-05-23 16:51
@lutzroeder has there been a change in API on latest release? I get this when I specify `port` here: 

```
netron.start(model_path, port=8080)

TypeError: start() got an unexpected keyword argument 'port'
```

**Comment by lutzroeder** [comment] 2021-05-23 17:15
`netron.start(model_path, 8080)`

**Comment by alexanderganderson** [comment] 2022-07-29 00:19
This has been bothering me for quite a while. 

```
import IPython

import netron
port = 6006
model_path = # <Your favorite model>
netron.start(model_path, 6006, browse=False)

IPython.display.IFrame(f"http://localhost:{port}", width=1000, height=1000)
```

I'm running everything locally, so I'm not sure if you need to enable another port in your case.

**Comment by lutzroeder** [comment] 2022-07-29 01:08
@alexanderganderson can you investigate and submit a pull request.

**Comment by lovettchris** [comment] 2023-02-08 02:04
`netron.start('model.onnx', 8081)` works great the first time, and auto-opens my web browser, which is fine, but the second time I do this in Jupyter, it spends a very long time saying `Stopping http://localhost:8081/`.  Can it "share" the server so if it's started once then it just serves up the next page instantly?

(I'm on Windows 11 doing this in VS Code version of Jupyter).

PS: I'd rather have the diagram show up inline inside the notebook.  IPython.display.IFrame works, but is not pretty because browser is also launched and I still have the netron.start problem above.

**Comment by lutzroeder** [comment] 2024-08-15 16:18
Duplicate of #1324

**Closed by lutzroeder** 2024-08-15 16:18 UTC
Labels: feature, help wanted
