### ISSUE TITLE
Full support for scikit-learn (joblib)

### ISSUE THREAD

**Issue by fkromer** [lutzroeder/netron#537] opened 2020-07-22 06:06 UTC
For recoverable estimator persistence scikit-learn recommends to use `joblib` (instead of `pickle`). Sidenote: It is possible to export trained models into ONNX or PMML but the estimators are not recoverable. For more info refer to [here](https://scikit-learn.org/stable/modules/model_persistence.html).

**Comment by lutzroeder** [comment] 2020-07-22 06:28
@fkromer can you please file a bug and provide repro steps and a sample file.

**Comment by lutzroeder** [comment] 2020-07-22 06:30
@fkromer can you please provide a sample file?

**Comment by fkromer** [comment] 2020-07-22 07:48
@lutzroeder Thanks a lot for the fast response. How can I share an exemplary `model.joblib` with you?

**Comment by lutzroeder** [comment] 2020-07-22 08:01
@fkromer Small files: Zip and drag into this response field. Large field: Upload to cloud drive and share link.

**Comment by fkromer** [comment] 2020-07-22 08:13
`We don’t support that file type with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.`

I've shared the example file for 7 days: https://web.tresorit.com/l/P34Vl#EWmpRSh8PcdWUQ8bhTK1nw

**Comment by fkromer** [comment] 2020-07-22 08:21
@lutzroeder Would be great if you got the example that I can get rid of it on my file share.

**Comment by lutzroeder** [comment] 2020-07-22 08:24
[dt.zip](https://github.com/lutzroeder/netron/files/4958780/dt.zip)

**Comment by lutzroeder** [comment] 2020-07-22 08:26
Dragged the file into the Netron window and seeing this...
<img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/438516/88153476-50500b00-cbba-11ea-80ec-12f0d7e7c794.png">

**Comment by lutzroeder** [comment] 2020-07-22 08:26
Duplicate of #180

**Comment by fkromer** [comment] 2020-07-22 08:27
> dt.zip

Great. Thanks a lot!

**Closed by lutzroeder** 2020-07-22 08:26 UTC
Labels: bug, no repro
