### ISSUE TITLE
Unable to open SDXL Turbo ONNX model from Hugging Face

### ISSUE THREAD

**Issue by kartikpodugu** [lutzroeder/netron#1256] opened 2024-04-05 08:26 UTC
- Netron app and version: 7.5.7 Desktop app

Steps to Reproduce:

1. Download the onnx model and external data from , [https://huggingface.co/stabilityai/sdxl-turbo/tree/main/unet](url)
2. Try to open the model in Netron desktop app

Facing same problem with browser netron app also. 

I am using Netron desktop app, and when I try to open the model, the Netron screen turns complete black and stays like that forever. I am using dark mode on the app.

**Comment by kartikpodugu** [comment] 2024-04-05 08:30
I ran ONNX model checker on the model, and it passes. 
Main problem is we are unable to understand if Netron is still trying to open the model, or it failed to open.
Even after leaving the app open for an hour or so, it doesn't open the model and also doesn't throw any error message, nor it crashes.

**Comment by kartikpodugu** [comment] 2024-04-05 08:31
Also, if I see the Task Manager, Netron consumes a lot of memory and CPU for a lot of time, but eventually it doesn't open the model.

**Comment by lutzroeder** [comment] 2024-04-05 15:19
Duplicate of #1214

**Closed by lutzroeder** 2024-04-05 15:19 UTC
Labels: bug
