### ISSUE TITLE
When I use netron to check yolov8 architecture, it dose not show any branch

### ISSUE THREAD

**Issue by JimXu1989** [lutzroeder/netron#1216] opened 2024-01-19 08:24 UTC
- Netron app and version: 7.3.8
- OS and browser version: Ubuntu 22.04

Steps to Reproduce:

1. download a yolov8.pt model  https://github.com/ultralytics/ultralytics
2. use netron to check it

you can find the model here: model  https://github.com/ultralytics/ultralytics
 netron does not show any branch

**Comment by lutzroeder** [comment] 2024-01-19 17:21
@JimXu1989 the model file contains only weights and the module hierarchy, not the architecture graph.

**Comment by lutzroeder** [comment] 2024-01-19 17:21
Duplicate of #720

**Closed by lutzroeder** 2024-01-19 17:21 UTC
Labels: bug
