### ISSUE TITLE
Command-line interface to save the visualized network to SVG or PNG

### ISSUE THREAD

**Issue by idy002** [lutzroeder/netron#311] opened 2019-08-03 14:51 UTC
Hi Lutz, 

Thank you for providing such a great tool. And I am wondering that could you provide the command-line interface to save the visualized network to SVG or PNG. When we are doing the Neural Architecture Search (NAS), there will be many networks that need to be visualized and it will be convenient if we can export the graph by command-line instead of by GUI. 

Thanks!

**Comment by lutzroeder** [comment] 2019-08-03 19:10
Duplicate of #162

**Closed by lutzroeder** 2019-08-03 19:10 UTC
Labels: duplicate
