### ISSUE TITLE
Does not show networks inside nn.ModuleList

### ISSUE THREAD

**Issue by palakons** [lutzroeder/netron#690] opened 2021-02-25 16:15 UTC
- Netron app and version: online https://netron.app/
- OS and browser version: Version 88.0.4324.182 (Official Build) (64-bit) Edition	
Windows 10 Pro
Version	20H2
Installed on	‎11/‎27/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

[a.zip](https://github.com/lutzroeder/netron/files/6044286/a.zip)

Does not show networks inside nn.ModuleList

Steps to Reproduce:

1. upload attached model

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment] 2021-02-25 17:25
Duplicate of #621

**Closed by lutzroeder** 2021-02-25 17:25 UTC
Labels: bug
