### ISSUE TITLE
Paddle Lite support

### ISSUE THREAD

**Issue by Leonardo-Ding** [lutzroeder/netron#796] opened 2021-08-31 10:21 UTC
Hi, I'm a [Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/README_en.md) developer, I want to know extremely how netron can support Paddle-Lite .nb format visualization. Thanks.

**Comment by lutzroeder** [comment] 2021-09-02 00:10
@Leonardo-Ding can you please provide additional information. The `.nb` format does not seem to support versioning so any change to the format will break tooling for existing files?

**Comment by lutzroeder** [comment] 2021-09-02 00:10
Duplicate of #797

**Closed by lutzroeder** 2021-09-02 00:10 UTC
Labels: feature, help wanted, no repro
