### ISSUE TITLE
Error "Duplicate value 'IteratorGenNext' "  when visualizing tensorflow meta file

### ISSUE THREAD

**Issue by DivyenduDutta** [lutzroeder/netron#1277] opened 2024-05-13 16:23 UTC
- Netron app and version: 7.6.5 Netron Desktop app
- OS and browser version: Windows 11 64 bit (Build 22631) + Microsoft Edge Version 124.0.2478.97

Steps to Reproduce:

1. Open .meta file of saved tensorflow 1.x model using Netron desktop app

2. Loading gets stuck and after about 5mins, I get error "Duplicate value 'IteratorGenNext' " as shown below
![image](https://github.com/lutzroeder/netron/assets/37018242/1b8869a1-f74b-4d0e-ae69-4bba54383918)

I get the same error message when loading via the netron webapp

Model file which has the issue:
[checkpoint-36000.zip](https://github.com/lutzroeder/netron/files/15297302/checkpoint-36000.zip)

This isn't my model. Its a 3D motion prediction transformer model resulting from another research work. Hence Im not really aware of the intricacies of their model but their code restores the model just fine from the checkpoint and inference works fine as well. 

Any idea about what this error implies?

**Comment by lutzroeder** [comment] 2024-05-13 17:59
Duplicate of #1271

**Closed** 2024-05-13 17:59 UTC
Labels: bug
