### ISSUE TITLE
Why does the result only show small blocks in pth file?

### ISSUE THREAD

**Issue by rdyan0053** [lutzroeder/netron#1034] opened 2023-01-07 08:10 UTC
![image](https://user-images.githubusercontent.com/53009617/211140731-026ab88f-f42c-47b2-9642-a947faddb631.png)
Why is this result different from the official example? :(

**Comment by lutzroeder** [comment] 2023-01-07 16:16
Duplicate of #720

**Closed** 2023-01-07 16:17 UTC
Labels: bug
