### ISSUE TITLE
app hangs without any hints when opening a llama2 model

### ISSUE THREAD

**Issue by areschen2015** [lutzroeder/netron#1212] opened 2024-01-10 03:44 UTC
- Netron app and version: 7.3.7
- OS and browser version: Windows Server 2016 Std

Steps to Reproduce:

1.Start netron-7.3.7 on windows;
2.Click 'Open Model...', select a model file (llama2 70b);
3.Click 'yes' on poped dialog 'Large model detected.', then netron hangs without any hints for a long time;
4. Only close the netron window by 'Task manager->Netron->finish task'.

Please attach or link model files to reproduce the issue.

**Comment by lutzroeder** [comment] 2024-01-10 03:46
@areschen2015 please share the model file.

**Comment by areschen2015** [comment] 2024-01-10 12:31
@lutzroeder here is the model file, 3x
[0_llama2_70b.zip](https://github.com/lutzroeder/netron/files/13887653/0_llama2_70b.zip)

**Comment by lutzroeder** [comment] 2024-01-11 03:13
@areschen2015 the graph has 8000+ nodes and the graph layout would take a very long time to complete. This is explained by the warning dialog that is showing when opening the file.

<img width="260" alt="1212" src="https://github.com/lutzroeder/netron/assets/438516/b503949d-3249-4255-a5f4-412ee6884f66">

Duplicate of #68 and #1214

**Comment by lutzroeder** [comment] 2024-01-11 03:14
Duplicate of #68 and #1214

**Closed by lutzroeder** 2024-01-11 03:13 UTC
Labels: no repro, bug

**Comment by areschen2015** [comment] 2024-01-11 03:44
Is there any solution? Or other acceleration solutions, for example, we can render one half of nodes at opening time, then render the others.

**Comment by lutzroeder** [comment] 2024-01-11 04:11
@areschen2015 you can investigate, suggest a solution and submit a pull request that works for all file formats.

**Comment by areschen2015** [comment] 2024-01-15 11:08
@lutzroeder I found that the main time consumption is in dagre. layout(). Is the dagre integrated the latest version? Besides, do you consider integrating other layout algorithms, such as Sankey layout or force layout?

**Comment by lutzroeder** [comment] 2024-01-15 16:54
@areschen2015 `dagre.js` is not the latest version. The code is forked, optimized and runs faster. Experiments with other layout algorithms are welcome. Ideally submit a pull request adding to `dagre.js`.

**Comment by areschen2015** [comment] 2024-01-16 01:40
@lutzroeder I printed the execution time of functions in dagre.js as the attachment showing, which opened a llama2 model from node 0 to node 1943. The total time of dagre layout is 37 sec, the function initOrder() took 17.6 sec and the invoking of buildLayerGraph() took 6.9 sec. So initOrder() and buildLayerGraph() are the keys of performance optimization.
For the popular large language models with number of nodes at least 1000, netron should adapt them for user to use easily and quickly. So what is the development plan in the future?

**Comment by areschen2015** [comment] 2024-01-16 01:41
![Uploading netron-time.png…]()

**Comment by lutzroeder** [comment] 2024-01-16 04:30
@areschen2015 as referenced earlier, one approach is to capture a hierarchical structure when serializing the file. Given the large number of formats and serialization approaches there isn't a single answer. This would not improve the situation for large flat files that removed all hierarchies, like the one you shared. Faster graph layout algorithms cloud help. The planned work is that you are investigating and trying to come up with an implementation. Graph layout algorithms tend to be non-linear in complexity so the challenge here might be finding and implementing a different algorithm that works for these large graphs and can scale linearly. `buildLayerGraph` being a bottleneck of the current implementation is well understood and quite a bit of time has been invested in making this code run fast.

**Comment by uuser0748** [comment] 2024-01-23 03:59
@areschen2015 Hi, I'm trying to visualize ChatGLM3 with Netron, but I don't know which model file I should drag in. The bin.index.json file couldn't generate graph with lines but simply weight modules. So I'm wondering how did you generate llama2 graph? Did you merge the files together? Looking forward for your reply :-)
![37281705978914_ pic](https://github.com/lutzroeder/netron/assets/133834015/e27063c0-aab3-40b8-ad91-ec33b9d90d07)
![37291705982127_ pic](https://github.com/lutzroeder/netron/assets/133834015/2681efb6-f0ef-45f1-9470-886443cca444)
