### ISSUE TITLE
RangeError Maximum call stack size exceeded with MobileBert model

### ISSUE THREAD

**Issue by mehrdadh** [lutzroeder/netron#536] opened 2020-07-14 20:11 UTC
I tried to visualize the saved models from mobilebert and ran into this error. Here is a link to .pb files:
[https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/mobilebert_squad_savedmodels.tar.gz](https://storage.googleapis.com/cloud-tpu-checkpoints/mobilebert/mobilebert_squad_savedmodels.tar.gz)

However I tried with the tflite version from this link and it worked:
[https://storage.googleapis.com/download.tensorflow.org/models/tflite/bert_qa/mobilebert_float_20191023.tflite](https://storage.googleapis.com/download.tensorflow.org/models/tflite/bert_qa/mobilebert_float_20191023.tflite)

Please let me know if you need more information to reproduce the error.
Thanks

**Comment by lutzroeder** [comment] 2020-07-16 04:34
Duplicate of #68

**Closed** 2020-07-16 04:35 UTC
Labels: bug
