### ISSUE TITLE
Add feature map sizes，too

### ISSUE THREAD

**Issue by yao-ying** [lutzroeder/netron#310] opened 2019-08-03 13:04 UTC
Thank you for sharing this great project! I think like netscope (http://ethereon.github.io/netscope/#/editor), add the feature map size is really useful.
although,this issue had beem proposal before(https://github.com/lutzroeder/netron/issues/105), but now still miss the character. I think you can add it in the OUTPUTS option(output size). I am working on windows10. Thank you!

**Comment by yao-ying** [comment] 2019-08-03 13:17
It is very difficult to describe this feature in words. If your display the code(https://github.com/soeaver/caffe-model/blob/master/cls/resnet/deploy_resnet10-1x32d.prototxt) in netscope(http://ethereon.github.io/netscope/#/editor).  It is the blob shapes in netscope. you can see it. Thank you!

**Comment by lutzroeder** [comment] 2019-08-03 19:08
Duplicate of #71

**Closed by lutzroeder** 2019-08-03 19:08 UTC
Labels: duplicate
