### ISSUE TITLE
No file resources/app-update.yml

### ISSUE THREAD

**Issue by GiuseppeDiGuglielmo** [lutzroeder/netron#377] opened 2019-11-27 00:04 UTC
I have install netron on RH7 through snap.

I get the following error. I can still use the tool but I would like to get rid of the problem. Is there a solution?
```
$ netron 
Checking for update
Error: Error: ENOENT: no such file or directory, open '/snap/netron/22/resources/app-update.yml'
ENOENT: no such file or directory, open '/snap/netron/22/resources/app-update.yml'
```

**Comment by lutzroeder** [comment] 2019-11-27 02:14
@GiuseppeDiGuglielmo can you investigate how Electron apps are expected to handle this and submit a fix?

Do Snap apps update through the OS and the app updater should be skipped? If so how is this accomplished?

https://www.electron.build/configuration/snap
https://snapcraft.io/docs/electron-apps
https://electronjs.org/docs/tutorial/snapcraft

**Comment by lutzroeder** [comment] 2019-11-27 03:06
Duplicate of #166

**Closed** 2019-11-27 03:06 UTC
Labels: duplicate
