### ISSUE TITLE
Starting app with link to model url

### ISSUE THREAD

**Issue by enpasos** [lutzroeder/netron#867] opened 2022-01-18 11:52 UTC
I'm so happy to have netron. Very nice tool.

Is it possible to start the browser version with providing an external model.onnx link?

The idea is to provide a link to netron app on some page that has the model url included as a parameter such that netron opens together with the model.

**Comment by enpasos** [comment] 2022-01-18 11:57
At the moment I provide links to netron.app and model separately: 
https://enpasos.ai/muzero/How#onnx
I would like to improve the UX.

**Comment by lutzroeder** [comment] 2022-01-18 12:18
Duplicate of #811

**Closed by lutzroeder** 2022-01-18 12:18 UTC
Labels: feature

**Comment by lutzroeder** [comment] 2022-01-18 12:25
> At the moment I provide links to netron.app and model separately:
> https://enpasos.ai/muzero/How#onnx

"...for your browser the Neutron App." is a typo?

**Comment by enpasos** [comment] 2022-01-18 13:58
How cool ... works like a charm!

**Comment by enpasos** [comment] 2022-01-18 13:59
> > At the moment I provide links to netron.app and model separately:
> > https://enpasos.ai/muzero/How#onnx
> 
> "...for your browser the Neutron App." is a typo?

Ups ... thanx
