### ISSUE TITLE
Is PyTorch reading the network architecture correctly?

### ISSUE THREAD

**Issue by zsffuture** [lutzroeder/netron#763] opened 2021-07-05 09:54 UTC
![image](https://user-images.githubusercontent.com/39027951/124453519-060b6e00-ddba-11eb-9cf6-bba6e9d17b85.png)

**Comment by lutzroeder** [comment] 2021-07-05 11:14
Duplicate of #720

**Closed** 2021-07-05 11:14 UTC
