### ISSUE TITLE
4.5.5 windows version  question

### ISSUE THREAD

**Issue by chumingqian** [lutzroeder/netron#613] opened 2020-10-11 22:34 UTC
Hi, @lutzroeder :
      This  window  4.5.5 version , models cant  represent  any  arrow connection  on  .pth     and  cant  open .weigth  file,  did  i  don sth wrong,   i  just  down the  4.5.5exe  file, and the  run it.
  ( and  what 's function  of  exe.blockmap, i couldn't  run it)

**Comment by lutzroeder** [comment] 2020-10-11 23:00
Duplicate of #236

**Comment by lutzroeder** [comment] 2020-10-11 23:00
Duplicate of #472

**Closed by lutzroeder** 2020-10-11 23:00 UTC

**Comment by lutzroeder** [comment] 2020-10-11 23:01
Duplicate of #133

**Comment by lutzroeder** [comment] 2020-10-11 23:02
@chumingqian please share the actual files to reproduce the behavior.
