### ISSUE TITLE
Search by tensor shape, other features

### ISSUE THREAD

**Issue by Engineero** [lutzroeder/netron#744] opened 2021-05-28 16:59 UTC
It would be great if we could expand the search feature from just node names to include features of nodes (search for specific kernel shapes or activation functions, etc.) and tensor shapes.

This comes from a current need that I have where I'm getting some cryptic shape errors at run time in an ONNX model and tracking them down has been a real pain. It would be great if I could use this utility to quickly search for certain tensor shapes to find a starting point for my debugging.

Cheers!

**Comment by lutzroeder** [comment] 2021-05-28 18:41
Duplicate of #744

**Closed by lutzroeder** 2021-05-28 18:41 UTC
Labels: feature, no repro
