### ISSUE TITLE
Support grouping of Transformer Architecture Encoder-Decoder building blocks

### ISSUE THREAD

**Issue by GeorgeS2019** [lutzroeder/netron#822] opened 2021-10-09 11:38 UTC
The more complex transformer architecture (e.g. from ONNX) consists of a stacking of either encoder or decoder building blocks.  It will help if the Netron community can feedback how to make such complex graph network more intuitive to visualize with an overview of these building blocks.

Ideally these higher level building blocks are defined within the ONNX during export. 

Is there graph layout methods that can help in identifying these building blocks?

Recently, a Work-In-Progress attempt has been made on such feature. Here is a[ WIP output](https://github.com/fel88/Dendrite/issues/1) using [gpt2.onnx](https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/model/gpt2-10.onnx)

![image](https://user-images.githubusercontent.com/49812372/136656454-b4afa228-329a-44e2-91a4-317aa2ceb96e.png)

**Comment by lutzroeder** [comment] 2021-10-09 14:39
Duplicate of #68

**Closed** 2021-10-09 14:46 UTC
Labels: feature
