### ISSUE TITLE
Navigating large graphs

### ISSUE THREAD

**Issue by NikolasMarkou** [lutzroeder/netron#610] opened 2020-10-05 20:25 UTC
While navigating large graphs, it becomes tedious to follow the edges.
It would be preferable to have a button on the side panel (inputs and outputs) so that we could easily go to the specified node

**Comment by Fannettembrown** [comment] 2022-03-14 00:19
Copy paste a separate file away from your search bar

**Comment by lutzroeder** [comment] 2023-08-16 10:12
Duplicate of #1122

**Closed by lutzroeder** 2023-08-16 10:12 UTC
Labels: feature, help wanted

**Comment by NikolasMarkou** [comment] 2023-08-31 16:33
Thank you sir
