### ISSUE TITLE
Group and collapse nodes

### ISSUE THREAD

**Issue by Rob-Fletcher** [lutzroeder/netron#592] opened 2020-09-12 03:07 UTC
Would be nice if you could group and collapse nodes in the visualization. For instance int ResNet, select a block of nodes that would be a residual block and collapse that into one node. Can make things nicer if you are exploring more complicated or custom nets that use common backbones.

**Comment by lutzroeder** [comment] 2020-09-12 03:14
Duplicate of #68

**Closed by lutzroeder** 2020-09-12 03:14 UTC
Labels: feature
