### ISSUE TITLE
Leverage the all cores to speed up the performance on big model

### ISSUE THREAD

**Issue by gtvforever** [lutzroeder/netron#727] opened 2021-04-20 06:22 UTC
When we tried to open big model, like bert.  It took very long time. When i opened the task manager, i found only one core was occupied for each netron instance.

I'm wondering that it's possible to leverage all phsysical cores to speed up its performance

**Comment by lutzroeder** [comment] 2021-04-20 06:52
Duplicate of #727.

**Closed by lutzroeder** 2021-04-20 06:52 UTC
Labels: feature
