### ISSUE TITLE
Unsupported function torch.alias

### ISSUE THREAD

**Issue by shuokay** [lutzroeder/netron#951] opened 2022-08-23 09:32 UTC
- Netron app and version: main branch: b20aee00d318df97acea0262490b566aa6e3d020, python server
- OS and browser version: macOS 12.5.1 (21G83) 

Steps to Reproduce:

1. `python publish/python.py build start --browse`
2. open the attached qdq.pt file

There is no `torch.alias` function in pytorch, but has `at::alias` function defined in  `aten/src/ATen/native/native_functions.yaml`
```yaml
- func: alias(Tensor(a) self) -> Tensor(a)
  variants: method, function
  dispatch:
    CompositeExplicitAutograd: alias
```
The generated torchscript file code used torch.alias. indeed.
I think `torch.alias` is come from `torch.as_subclass` method, which I used to extend `torch.Tensor`, you can refer to https://pytorch.org/docs/stable/notes/extending.html#extending-torch-with-a-tensor-wrapper-type for more infomation.

I have tried to add `torch.alias` in pytorch-metadata.json,  and the torchscript file can be visualized but lost some edges.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/5029591/186124188-03966a08-4468-418e-8dfa-c0ec9b345734.png">

Please attach or link model files to reproduce the issue if necessary.
[qdq.pt.zip](https://github.com/lutzroeder/netron/files/9401259/qdq.pt.zip)

**Comment by lutzroeder** [comment] 2022-08-23 09:57
@shuokay what is the definition of `ops.horizon.bpu_scale_dequantization`?

**Comment by lutzroeder** [comment] 2022-08-23 09:59
Duplicate of #947

**Closed by lutzroeder** 2022-08-23 09:59 UTC
Labels: bug

**Comment by shuokay** [comment] 2022-08-23 10:05
@lutzroeder `ops.horizon.bpu_scale_dequantization` is a custom defined dequantze op, supporting perchannel and pertensor quantize at the same time.
```cpp
at::Tensor bpu_scale_dequantization(
    const at::Tensor& data,
    const at::Tensor& scale,
    const int64_t ch_axis) 
```

**Comment by shuokay** [comment] 2022-08-23 10:06
Do you mean I should also add `bpu_scale_dequantization ` to  `pytorch-metadata.json`?

**Comment by shuokay** [comment] 2022-08-23 10:17
@lutzroeder When adding all used ops in pytorch-metadata.json, the model can be visualized correctly, thank you for your great work~

**Comment by lutzroeder** [comment] 2022-08-23 14:19
There are multiple overloads for `ops.horizon.bpu_scale_dequantization`.
```
_2 = ops.horizon.bpu_scale_quantization(input, scale, zero_point, _1, info.min, info.max, dtype, march)
_3 = ops.horizon.bpu_scale_dequantization(input, scale, ch_axis)
```
What repository or package defines `ops.horizon`.

**Comment by shuokay** [comment] 2022-08-23 14:33
@lutzroeder 
They are private ops and they are `quantization` and `dequantization` , not overloads.
I have visualized the model correctly after add all used custom ops into pytorch-metadata.json. Many thanks for your help.

PS: I find it is a little hard to understand Netron source code (for example, there are more than 3k lines in python.js), it would be even better if you could add some documentation to make it easier for others to develop
