### ISSUE TITLE
add support to visualize feature map shape

### ISSUE THREAD

**Issue by fortuneko** [lutzroeder/netron#409] opened 2020-01-09 07:12 UTC
Hi, 
   I love this tool very much,thanks a lot for your great job! 
   When I use this tool to visualize network structure, it would be more helpfull to display the feature map shape of each layer, with the input data shape and kernerl shape, the feature map shape could be computed as a result.
  With the feature map shape, it would be more easier to analyze model network.

**Comment by lutzroeder** [comment] 2020-01-09 07:19
Duplicate of #71

**Closed by lutzroeder** 2020-01-09 07:19 UTC
