### ISSUE TITLE
[Ubantu 18.04] How to save the visualization result  loaclhost:8080  to .html

### ISSUE THREAD

**Issue by daydayfun** [lutzroeder/netron#523] opened 2020-06-17 02:48 UTC
I'm using this tool in Ubantu 18.04.
The visualization result is in localhost:8080, the result is execllent.  But I don't know how to save the result as a file.(such as resnet50.html/mlp.html/mobilenet.html...)

Can you help me fix the requirement, thanks very much!

**Comment by daydayfun** [comment] 2020-06-17 02:50
I try to modify server.py to save the  visualization result, but failed...

**Comment by lutzroeder** [comment] 2020-06-17 02:54
Duplicate of #162

**Closed by lutzroeder** 2020-06-17 02:54 UTC

**Comment by daydayfun** [comment] 2020-06-17 06:08
Thanks very much,  I'm going to use the offline Appimage

**Comment by lutzroeder** [comment] 2020-06-17 06:18
The browser version includes these options:

<img width="610" alt="screenshot" src="https://user-images.githubusercontent.com/438516/84862235-acf26000-b027-11ea-9889-4feb9a7fcc69.png">

**Comment by daydayfun** [comment] 2020-06-17 08:06
How to use the appImage in command line, can you help me with some example
