### ISSUE TITLE
PyTorch: The calculation graph is not complete.

### ISSUE THREAD

**Issue by EkAugust** [lutzroeder/netron#722] opened 2021-04-13 15:56 UTC
- Netron app and version: Desktop app 4.8.8
- OS and browser version: macOS 11.2.3 
- Framework: Pytorch 1.8

Steps to Reproduce:

1. Define a ResNet18 model and save the model file as  *.pkl
2. Open Netron.app and open the model file
3. The calculation graph doesn't show detailed layers information in Basic blocks. It only present the name of sequential container. Meanwhile, the link arrows of sequential containers seem not correct, too.

Does it mean I should unpack sequential containers to obtain the correct calculation graph?

**Comment by lutzroeder** [comment] 2021-04-13 19:43
@EkAugust can you share a sample model file or repro steps?

**Comment by lutzroeder** [comment] 2021-09-12 20:55
Duplicate of #720

**Closed by lutzroeder** 2021-09-12 20:55 UTC
Labels: no repro, bug
