### ISSUE TITLE
python example: export model image as png/svg

### ISSUE THREAD

**Issue by gracesrm** [lutzroeder/netron#317] opened 2019-08-08 20:03 UTC
I have a lot of models to virtualize, and I'm finding a way to automize.

I know in python I can use the following

`import netron; netron.start('[FILE'])`

Can you give an example of how I can export the image result to PNG/SVG?

Thanks a lot.

**Comment by lutzroeder** [comment] 2019-08-08 20:16
Duplicate of #162

**Closed** 2019-08-08 20:16 UTC
Labels: duplicate
