### ISSUE TITLE
model comparison in netron 

### ISSUE THREAD

**Issue by mikekml** [lutzroeder/netron#937] opened 2022-07-27 15:49 UTC
Hi Lutz, 

Thank you for the Netron, we use it on a regular basis.  Have you ever considered to add possibility to compare networks, like you would compare source code in meld. We are working on optimizations of neural nets and just use two Netrons side by side to visualize changes.   Appreciate your thoughts. 

Thanks, 
-Mike

**Comment by lutzroeder** [comment] 2022-07-27 23:25
Duplicate of #705

**Closed by lutzroeder** 2022-07-27 23:25 UTC
Labels: feature
