### ISSUE TITLE
TorchScript: Unsupported function 'torch.broadcast_to'

### ISSUE THREAD

**Issue by pbsds** [lutzroeder/netron#920] opened 2022-06-06 15:23 UTC
- Netron app and version: website 5.8.5
- OS and browser version: Firefox 100.0.2 on Linux 5.15.41-1-MANJARO

# Steps to Reproduce:

1. use `torch.broadcast_to` or `torch.Tensor.broadcast_to` in a module
2. export
3. load in Netron

# Please attach or link model files to reproduce the issue if necessary.

![image](https://user-images.githubusercontent.com/140964/172191399-fa340555-7af4-4dd1-a5f8-0fac5c49da2e.png)

repro.

```python
import torch

class Test(torch.nn.Module):
    def forward(self, a, b):
        shape = torch.broadcast_shapes(a.shape, b.shape)
        return torch.cat((a.broadcast_to(shape), b.broadcast_to(shape)), dim=-1)

torch.jit.trace(
    Test(),
    (torch.ones(2, 1, 3), torch.ones(1, 4, 3)),
).save("foobar.pt")
```

**Comment by lutzroeder** [comment] 2022-06-08 01:24
Duplicate of #637

**Closed by lutzroeder** 2022-06-08 01:24 UTC
Labels: bug
