### ISSUE TITLE
Does Netron app stores any data?

### ISSUE THREAD

**Issue by thanos-wandb** [lutzroeder/netron#968] opened 2022-09-13 17:17 UTC
Hi @lutzroeder I was wondering if the [web app](https://netron.app) saves any data from a loaded model?

**Comment by lutzroeder** [comment] 2022-09-13 18:10
Currently no data is stored permanently. For telemetry see below.

**Comment by lutzroeder** [comment] 2022-09-13 18:10
Duplicate of #853

**Closed by lutzroeder** 2022-09-13 18:10 UTC
