### ISSUE TITLE
Runtime field clarification request

### ISSUE THREAD

**Issue by 21kc-caracol** [lutzroeder/netron#754] opened 2021-06-16 05:49 UTC
In Netron model viewer, what does the "runtime" field means?

Is it the TensorFlow version that used to create this model? 
[https://i.stack.imgur.com/ko6E5.png](Screenshot of Netron model properties section)

**Comment by lutzroeder** [comment] 2021-06-16 05:52
Duplicate of #753

**Closed by lutzroeder** 2021-06-16 05:52 UTC
