### ISSUE TITLE
visualize pth file of Pytorch

### ISSUE THREAD

**Issue by ardeal** [lutzroeder/netron#472] opened 2020-04-22 06:54 UTC
Hi,

I use Netron tool to visualize the pth file from the following link:
https://download.pytorch.org/models/vgg19_bn-c79401a0.pth

If I use Netron tool to visualize some other format file, there are arrow-lines to connect each layer of the network. 

but the visualized output network of pth file seems not correct. there is no arrow-lines to connect each layer....

Thanks,
Ardeal

**Comment by lutzroeder** [comment] 2020-04-22 07:02
The file contains only tensor weights and no graph information. Load the weights in PyTorch and export to ONNX to get a file that includes the graph.

**Comment by lutzroeder** [comment] 2020-04-22 07:02
Duplicate of #133

**Closed by lutzroeder** 2020-04-22 07:02 UTC

**Comment by ardeal** [comment] 2020-04-22 08:22
@lutzroeder ,
Hi,

I am still confused about how to convert the pth file to onnx file.

at present, I do save the pth file with code:
torch.save(model.state_dict(), filepath)

according to #133 , I got 2 understandings:
1) re-train the model and save the pth file with code: torch.save(model, filepath)
2) don't need to re-train the model. I need to use some code to convert the pth file to onnx file. what the code should be? is there any example code?

which of my upper understandings is correct?

Thanks,
Ardeal

**Comment by lutzroeder** [comment] 2020-10-25 19:57
[boolean.zip](https://github.com/lutzroeder/netron/files/5435842/boolean.zip)

**Comment by lutzroeder** [comment] 2023-01-07 18:29
`wget https://api.ngc.nvidia.com/v2/models/nvidia/megatron_bert_345m/versions/v0.1_cased/zip -O megatron_bert_345m_v0.1_cased.zip`

**Comment by lutzroeder** [comment] 2024-08-04 22:40
Duplicate of #720
