### ISSUE TITLE
Add support to visualize the DLC model format

### ISSUE THREAD

**Issue by MeghnaNatraj** [lutzroeder/netron#1101] opened 2023-05-22 17:46 UTC
The DLC file extension is a ML model format that is currently not supported by Netron. 

Reference:

- [SNPE tool to convert Caffe / TensorFlow models to DLC format](https://developer.qualcomm.com/sites/default/files/docs/snpe/overview.html)

**Comment by lutzroeder** [comment] 2023-05-22 17:51
Duplicate of #1101

**Closed by lutzroeder** 2023-05-22 17:51 UTC
Labels: feature

**Comment by lutzroeder** [comment] 2023-05-22 17:53
@MeghnaNatraj please share a model file, the format specification as some formats are undocumented and a pull request adding support.

**Comment by lutzroeder** [comment] 2023-05-22 17:54
Duplicate of #640
