### ISSUE TITLE
TorchScript: Unsupported function 'torch.roll'

### ISSUE THREAD

**Issue by cds221** [lutzroeder/netron#957] opened 2022-08-31 05:21 UTC
I'm working on video swin transformer recently, but Netron doesn't support torch.roll() function in it. Could you sovle this problem?

model link: https://drive.google.com/file/d/1vcfOFaMXQv28C84bWZCb_uQUYLzMeHar/view?usp=sharing

thanks for your help

**Comment by lutzroeder** [comment] 2022-08-31 08:22
Duplicate of #950

**Closed by lutzroeder** 2022-08-31 08:22 UTC
Labels: bug

**Comment by cds221** [comment] 2022-08-31 08:25
> #950的副本[](https://github.com/lutzroeder/netron/issues/950)

But this problem is not solved

**Comment by cds221** [comment] 2022-08-31 08:25
> #950的副本[](https://github.com/lutzroeder/netron/issues/950)

But this problem is not solved
