### ISSUE TITLE
OpenVINO weights support

### ISSUE THREAD

**Issue by GlebKazantaev** [lutzroeder/netron#307] opened 2019-07-29 12:12 UTC
OpenVINO models (IRs) contains XML and BIN files. For now Netron loads only XML file with topological description. And it would be great if Netron will load weights from BIN file and display values as implemented in other frameworks (like in ONNX).
![image](https://user-images.githubusercontent.com/18436845/62047352-ee60fd80-b212-11e9-8c6c-dc597d4dad75.png)

All information about offsets, sizes and types of tensor can be found in XML.

Note: BIN files are optional an may not exists in the same folder with XML file.

**Comment by lutzroeder** [comment] 2019-07-29 18:11
Duplicate of #191. @demid5111

**Comment by lutzroeder** [comment] 2019-10-07 01:13
@GlebKazantaev @demid5111 What format are `.bin` files stored in? Is it possible to detect the `.bin` format from other `.bin` files which use the same extension but are not generated by OpenVINO?

**Comment by lutzroeder** [comment] 2019-11-15 05:08
@demid5111

**Closed** 2019-12-30 04:18 UTC
Labels: help wanted
