### ISSUE TITLE
[TF2][GraphDef] Make Const hide in the operators' initializers

### ISSUE THREAD

**Issue by FrozenGene** [lutzroeder/netron#808] opened 2021-09-19 03:48 UTC
Hi @lutzroeder , thanks for creating this cool tool. 

In TF2 graphdef visualization, our const doesn't be hidden in the operators' in initializers attribute like our TF1 support. For example, in just one simple minist model, we will have this:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/7287321/133914697-56acf821-2ee0-4266-83bb-80591f86a54b.png">

It will be look very weird when our model have many const node (or  simply many convolution ops).

If we open one TF1 model, we could have nice visualization:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/7287321/133914761-aa4bc366-a682-4577-8ad9-5cc2b6a1a2f7.png">

Could we support TF2 graphdef like TF1? Or you could point me where I could modify the code to do this. Thanks in advance.

**Comment by lutzroeder** [comment] 2021-09-19 03:49
Duplicate of #342

**Closed by lutzroeder** 2021-09-19 03:49 UTC
Labels: feature
