### ISSUE TITLE
SSD MobileNetv1 has missing connections

### ISSUE THREAD

**Issue by phager90** [lutzroeder/netron#587] opened 2020-08-27 12:51 UTC
- Netron app and version: Desktop app, 4.4.7
- OS and browser version: Windows

Steps to Reproduce:

1. Download ONNX Model:
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_10.onnx?raw=true
2. Open in Netron

Class Prediction sub-graph appear to be not connected:

![image](https://user-images.githubusercontent.com/9904169/91443503-b859d700-e873-11ea-832c-f3c6c02fd479.png)

It seems that the connection 'Postprocessor/Slice:0' is not drawn.

Network was converted following the steps here:
https://github.com/onnx/tensorflow-onnx/blob/cbffde47336da58e01d0eb670c3ddb482f661ca8/tutorials/ConvertingSSDMobilenetToONNX.ipynb
(Note that network runs correctly when executed with ONNX runtime)

**Comment by lutzroeder** [comment] 2020-08-27 15:31
Duplicate of #535

**Closed by lutzroeder** 2020-08-27 15:31 UTC
Labels: bug
