### ISSUE TITLE
TensorIterator in OpenVINO IR is visualized differently

### ISSUE THREAD

**Issue by rnugmanx** [lutzroeder/netron#766] opened 2021-07-09 15:55 UTC
- Netron app and version: 4.9.8 Desktop app, 5.0.0 Website
- OS and browser version: Windows 10, Chrome 91.0.4472.124
![image](https://user-images.githubusercontent.com/65988046/125105507-3408ef00-e0e7-11eb-9f57-8a32e80c5056.png)

Steps to Reproduce:
1. Followed the link to A3C model and converted it to IR https://docs.openvinotoolkit.org/2020.1/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html 

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment] 2021-07-09 17:52
@rnugmanx Please reach out the the OpenVINO team at Intel to investigate this.

**Comment by lutzroeder** [comment] 2021-07-09 17:52
Duplicate of #191

**Closed by lutzroeder** 2021-07-09 17:52 UTC
Labels: bug
