### ISSUE TITLE
TensorRT support

### ISSUE THREAD

**Issue by Qiancj0605** [lutzroeder/netron#803] opened 2021-09-09 02:53 UTC
Can netron visualize TRT models？
I tried it, and netron doesn’t seem to be able to visualize the TRT model。
Is there a way to visualize the TRT model？Thanks。

**Comment by lutzroeder** [comment] 2021-09-09 03:52
`.trt` is an undocumented format and hence cannot be supported. Please ask the creators of the format.

**Comment by lutzroeder** [comment] 2021-09-09 03:54
Duplicate of #533

**Closed by lutzroeder** 2021-09-09 03:54 UTC
Labels: feature, no repro

**Comment by lutzroeder** [comment] 2024-07-20 22:06
Duplicate of #725
