### ISSUE TITLE
Pytorch model visualization issue?

### ISSUE THREAD

**Issue by AI-Hunter** [lutzroeder/netron#858] opened 2021-12-27 10:21 UTC
Can not see the connection in netron.
Would you tell me please why? it shows only module
![image](https://user-images.githubusercontent.com/94281395/147462310-f667971f-fb76-45ca-8845-4f834c9d99af.png)

**Comment by lutzroeder** [comment] 2021-12-27 14:32
Duplicate of #720

**Closed** 2021-12-27 14:46 UTC
Labels: no repro
