### ISSUE TITLE
Python code to export model architecture to PNG file

### ISSUE THREAD

**Issue by hoangminhq5310** [lutzroeder/netron#626] opened 2020-11-19 02:23 UTC
It would be nice if the tool had the "export to PNG" so people can automate the process in python code, for example:

```
import torch
import torchvision.models as models
import netron 

x = torch.zeros(1, 3, 224, 224, dtype=torch.float, requires_grad=False)
resnet = models.resnet50(pretrained=True)
traced_resnet = torch.jit.trace(resnet, x)
torch.jit.save(traced_resnet, 'resnet.pth')
netron.start('resnet.pth')
netron.export_to_PNG('resnet.pth', 'resnet_architect.png')
```

**Comment by lutzroeder** [comment] 2020-11-19 04:56
Duplicate of #450

**Closed by lutzroeder** 2020-11-19 04:56 UTC
Labels: feature
