### ISSUE TITLE
Export ONNX model as image using netron python library

### ISSUE THREAD

**Issue by murtazabasu** [lutzroeder/netron#713] opened 2021-03-30 10:28 UTC
Hello I have a pytorch model that I can successfully export it to a onnx and then using Netron App open the model and visualize it. But for my purpose, I would like to save the visualized model as a image using python.

Now of course, in the Netron application there is a option of exporting and saving the file as image. But I would prefer doing this in python.

There is a pip library for netron available but as far as I know, it only opens the model in the browser using netron.start('file_path')  I couldn't find any function to export the model to a image.

Is there a way around?

**Comment by lutzroeder** [comment] 2021-03-30 11:13
Duplicate of #162

**Closed by lutzroeder** 2021-03-30 11:13 UTC
Labels: feature
