### ISSUE TITLE
MindSpore: MSL1 format is deprecated

### ISSUE THREAD

**Issue by wikiwen** [lutzroeder/netron#762] opened 2021-07-02 02:11 UTC
- Netron app and version: 5.0.0
- OS and browser version: windows10, Chrome 91

Steps to Reproduce:

1. open file [control_flow_ut_while_0122.ms](https://github.com/lutzroeder/netron/files/6097971/control_flow_ut_while_0122.ms.zip)
2. Netron will pop up a window: Error loading MindSpore Lite model, MSL1 format is deprecated

Does it means mindspore lite v1.1 is depredcated? But the latest mindspore lite version is v1.2, why it has no compatibility with the near versions? I try to find old netron install package, but i can only find v5.0.0 and v4.9.9 in https://github.com/lutzroeder/netron/releases. 

So any solutions?

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment] 2021-07-02 02:34
@YvetteLaw

**Comment by lutzroeder** [comment] 2021-07-02 02:35
Duplicate of #676

**Closed by lutzroeder** 2021-07-02 02:35 UTC
Labels: bug

**Comment by wikiwen** [comment] 2021-07-02 02:49
> Duplicate of #676
Thank you for your reply, I have seen YvetteLaw's explanation about this compatibility problem. Does it be ok if I degrade netron to a lower version? And where can i find a old windows install package, which can open mindspore lite v1.1 model?
