### ISSUE TITLE
Failed to visualize Pytorch JIT model with output predictions as a dictionary

### ISSUE THREAD

**Issue by geogeo28** [lutzroeder/netron#678] opened 2021-02-04 03:37 UTC
Version: 4.7.3 Desktop app, macOS 10.15.6 (19G73)
Steps to Reproduce:

Load dummy.pt which returns a dict in forward method.
<img width="1015" alt="Screen Shot 2021-02-03 at 7 35 08 PM" src="https://user-images.githubusercontent.com/11450275/106841426-f21adf00-6656-11eb-8d7e-0c64cc50c189.png">

[dummy.pt.zip](https://github.com/lutzroeder/netron/files/5922993/dummy.pt.zip)

```
import torch.jit
import torch.nn as nn
class DummyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self._conv1 = nn.Conv2d(4, 8, 3, padding=1)
        self._conv2 = nn.Conv2d(8, 16, 3, padding=1)
        self._conv3 = nn.Conv2d(16, 24, 3, padding=1)
        self._conv_aux = nn.Conv2d(4, 24, 3, padding=1)

    def forward(self, input: torch.Tensor):
        y1 = self._conv1(input)
        y2 = self._conv2(y1)
        y3 = self._conv3(y2)
        aux = self._conv_aux(input)
        return {
            'pred': [None, y2, y3],
            'aux': [aux, None, None]
        }

model = DummyModel()
model_jit = torch.jit.script(model)
model_jit.save('/tmp/dummy.pt')

```

**Comment by lutzroeder** [comment] 2021-02-04 03:53
Duplicate of #677

**Closed by lutzroeder** 2021-02-04 03:53 UTC
Labels: bug
