### ISSUE TITLE
Is there a tutorial to add support of a new framework

### ISSUE THREAD

**Issue by LucasMahieu** [lutzroeder/netron#1307] opened 2024-06-30 12:06 UTC
I am wondering if you already have some documentation / tutorial / example to illustrate how to add a new framework supported by netron ?

I would appreciate it :) 

by the way, thanks for the great job ! Netron is one our more basic tool in our toolbox now 👍

**Comment by lutzroeder** [comment] 2024-06-30 16:46
Duplicate of #1308

**Closed by lutzroeder** 2024-06-30 16:46 UTC
Labels: feature
