### ISSUE TITLE
Export: Caffe to ONNX

### ISSUE THREAD

**Issue by jnulzl** [lutzroeder/netron#831] opened 2021-10-20 03:04 UTC
Netron could visual ONNX, TensorFlow Lite, Keras, Caffe format and so on  

Hope to support "save as"  function, such as:  from caffe save as to onnx 
and even from one of {caffe, onnx, mnn, ncnn, tflite} to one of {caffe, onnx, mnn, ncnn, tflite}

**Comment by lutzroeder** [comment] 2021-10-20 04:21
Duplicate of 415

**Closed by lutzroeder** 2021-10-20 04:21 UTC
Labels: feature

**Comment by lutzroeder** [comment] 2025-04-03 13:48
Duplicate of #415

**Comment by lutzroeder** [comment] 2025-04-03 13:55
Duplicate of #1445
