### ISSUE TITLE
Search layers by dtype

### ISSUE THREAD

**Issue by GustavoStahl** [lutzroeder/netron#634] opened 2020-11-28 12:09 UTC
It would be nice if the **Find** tool could filter also by data type (e.g. float32, int32). While working with conversions from TF➙Onnx and quantization, a lot of problems comes from dtypes that shouldn't be there, so searching through them could help users find where the struggle is happening.

**Comment by lutzroeder** [comment] 2020-11-28 18:31
Duplicate of #542

**Closed by lutzroeder** 2020-11-28 18:31 UTC
Labels: feature
