### ISSUE TITLE
Listing operators used in model

### ISSUE THREAD

**Issue by mttjcksn** [lutzroeder/netron#949] opened 2022-08-18 08:12 UTC
Hey, thanks for Netron, it's a very convenient tool. 

I'm testing some large models on various inferencing platforms and finding problems with not all model operators being supported - for example 'Erf' operator on ONNX.js.

It would be useful to be able to load a model into Netron and get a list of all operators it uses so I can cross-reference with the supported operators of the inferencing platform.

Thanks :)

**Comment by lutzroeder** [comment] 2022-08-18 08:23
Duplicate of #204

**Closed by lutzroeder** 2022-08-18 08:23 UTC
Labels: feature
