### ISSUE TITLE
paddle __model__ file can't be selected under macos

### ISSUE THREAD

**Issue by dwSun** [lutzroeder/netron#747] opened 2021-06-03 08:15 UTC
- Netron app and version: 4.9.5 Desktop app
- OS and browser version: macOS 11.4

![image](https://user-images.githubusercontent.com/5899962/120611607-f0d3b480-c486-11eb-9aa2-7999b44f7a20.png)

**Comment by lutzroeder** [comment] 2021-06-03 10:51
Duplicate of #443 and #554

**Closed by lutzroeder** 2021-06-03 10:51 UTC
Labels: bug
