### ISSUE TITLE
Unsupported RKNN container version 4

### ISSUE THREAD

**Issue by SccotMu** [lutzroeder/netron#1097] opened 2023-05-14 14:41 UTC
- Netron app and version: <6.8.8.exe> and <6.8.9.exe> 

1. Unsupported RKNN container version [4], but 5.9.8.exe support.
2. 
![55f6dc6796b11415c21629e4f7b325a](https://github.com/lutzroeder/netron/assets/52561068/92823049-9d52-4bf1-b4a8-1e7756637290)

model download [link](https://pan.baidu.com/s/1Xsg3riwKHLj0lqRU2RRSWg 提取码: wmie)

**Comment by lutzroeder** [comment] 2023-05-14 15:22
@SccotMu the download is not available. Please provide a pull request or documentation for this format.

**Comment by lutzroeder** [comment] 2023-05-14 15:23
Duplicate of #639

**Closed by lutzroeder** 2023-05-14 15:22 UTC
Labels: no repro, bug
