### ISSUE TITLE
Not exporting to PNG/SVG

### ISSUE THREAD

**Issue by LuisTbx** [lutzroeder/netron#869] opened 2022-01-19 10:24 UTC
Using the SNAP version of NETRON, when exporting files no output is generated. Perhaps some missing dependency? Using an ONNX model.

Interestingly, when the export name points to an existing file the export works. Perhaps it is a permission issue.

**Comment by lutzroeder** [comment] 2022-01-19 12:25
Duplicate of #861

**Closed by lutzroeder** 2022-01-19 12:25 UTC
