### ISSUE TITLE
TFLite: Support custom attributes

### ISSUE THREAD

**Issue by lgeiger** [lutzroeder/netron#591] opened 2020-09-07 15:53 UTC
Netron is awesome for viewing TFLite models, however the custom ops don't correctly render custom options, but show the raw uint8 flexbuffer array which is not easily human readable:
![Screenshot 2020-09-07 at 17 47 39](https://user-images.githubusercontent.com/13285808/92403757-7150c900-f132-11ea-9270-482e135624f3.png)

It would be great if Netron would correctly render custom felxbuffer options. Recently there was an official [JS Flexbuffer implementation](https://github.com/google/flatbuffers/blob/master/js/flexbuffers.js) added that could be used to convert the raw data into human readable key value pairs.

I attached an [example network](https://github.com/lutzroeder/netron/files/5183913/quicknet.tflite.zip) with custom ops that could be used for testing.

**Comment by lutzroeder** [comment] 2020-09-07 21:25
Duplicate of #499

**Closed by lutzroeder** 2020-09-07 21:25 UTC
Labels: feature

**Comment by lgeiger** [comment] 2020-09-07 22:51
Sorry I missed #499.

I briefly looked into fixing this issue. For reference: it looks like there is currently a bug in JS flexbuffer support https://github.com/google/flatbuffers/issues/5949#issuecomment-688421193 that prevents this from working correctly with the example network I posted.
