### ISSUE TITLE
Batch mode for figure export?

### ISSUE THREAD

**Issue by DrChainsaw** [lutzroeder/netron#494] opened 2020-05-16 19:54 UTC
Is there a way to progamatically export a png given a model file, something like `netron.exe -m model.onnx -png model.png`?

Use case is that I'd like to put it in the loop when doing neural architecture search so that it afterwards is possible to visualize how the architecture evolved.

**Comment by lutzroeder** [comment] 2020-05-16 19:59
Duplicate of #162

**Closed by lutzroeder** 2020-05-16 19:59 UTC
