### ISSUE TITLE
Hierarchical expansion of large graphs

### ISSUE THREAD

**Issue by jenniferzhu** [lutzroeder/netron#68] opened 2018-01-24 06:11 UTC
I failed to load 2.1 MB .meta file generated from char-rnn model (https://github.com/sherjilozair/char-rnn-tensorflow) with python 2.7 and tensorflow 1.0.

It is loading forever... I am wondering what is wrong with these files?

**Comment by lutzroeder** [comment] 2018-01-24 06:13
How did you produce the `.meta` file? Can you share it?

**Comment by lutzroeder** [comment] 2018-01-24 06:38
The graph has more than 5000 nodes and the graph layout is choking. Tried running GraphViz and it's running forever as well. Those graphs will need an expand and explore UI that avoids rendering the entire graph. TensorFlow support is pretty experimental at this point.

**Comment by jenniferzhu** [comment] 2018-01-24 22:50
Thanks @lutzroeder 
I hope there would be some ways to workaround this issue, since I really like Netron's image of models.

**Comment by erwincoumans** [comment] 2019-03-26 15:02
Same issue, meta file is here in case you want to test it:
https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_data/policies/ppo/minitaur_reactive_env/model.ckpt-14000000.meta

**Comment by srikanthdevalour** [comment] 2019-07-19 10:44
Netron doesnot show FC layer in the diagram. I need to view the weights of the FC layer. Is there anything we can do it view Fully Connected layer.

**Comment by lutzroeder** [comment] 2019-07-19 21:13
@srikanthdevalour can you create a new issue and add a sample file.

**Comment by kobemini** [comment] 2019-12-05 06:00
@lutzroeder You mentioned "Those graphs will need an expand and explore UI that avoids rendering the entire graph" , are there any improvements planned for release versions in the future?

**Comment by jojivk73** [comment] 2020-04-13 16:49
For large graphs, is it possible to add an option to show a given node +  fanin and fanouts upto specified level.
Example netron <g.pbtxt> -node <node_name> -level 3

**Comment by JasonWayne** [comment] 2020-09-08 08:02
@jojivk73  there is no such args like node or level in my netron cmd line...

**Comment by yairb-gm** [comment] 2021-09-12 09:52
Hi, I'm encountering this issue as well for models I was able to open with previous versions, of onnx files

**Comment by lutzroeder** [comment] 2021-09-12 17:01
@yairb-gm can you share a sample file to reproduce the issue.

**Comment by Fannettembrown** [comment] 2022-03-14 00:26
Also check an see if your branch system has a Flutter system....

**Comment by CarlPoirier** [comment] 2022-03-18 17:49
Hi @lutzroeder,

I've seen there was EfficientDet-D0 mentioned in the other issue about this. It does work now, but Netron still barfs on EfficientDet-D2. [Here](https://bit.ly/3qjoUxz) is an example onnx file. I'm not very fluent in javascript, is there anything I can do quickly to get this fixed?

Thanks,

Carl

**Comment by lutzroeder** [comment] 2022-09-28 01:35
pytorch/pytorch#75100

**Comment by ZhangGe6** [comment] 2024-09-01 15:43
Hi folks. I developed [`netron-hierarchy`](https://github.com/ZhangGe6/netron-hierarchy), based on netron codebase and enables visualize models in a hierarchical way. This may be worth a try, especially for LLM models. Hope it helps!

**Comment by lutzroeder** [comment] 2024-09-28 17:44
Duplicate of #1370

**Closed by lutzroeder** 2024-09-28 17:44 UTC
Labels: feature
