### ISSUE TITLE
Delete key is not working in find input box

### ISSUE THREAD

**Issue by ice-tong** [lutzroeder/netron#1201] opened 2023-12-01 03:01 UTC
- Netron app and version:  7.3.1 Python Server
- OS and browser version:  Ubuntu 20.04

Steps to Reproduce:

1. `pip install netron==7.3.1`
2. Use `netron xxxx.onn` to  open a onnx model in browser.
3.  Press `ctrl + F` to find a string. In the input box the (Delete / Backspace) key is not working.

Please attach or link model files to reproduce the issue.

**Comment by lutzroeder** [comment] 2023-12-01 03:19
Duplicate of #1195

**Closed by lutzroeder** 2023-12-01 03:19 UTC
Labels: bug
