### ISSUE TITLE
netron close but memory not released on windows 10!

### ISSUE THREAD

**Issue by ou-zhi-hui** [lutzroeder/netron#332] opened 2019-09-11 09:57 UTC

**Comment by ou-zhi-hui** [comment] 2019-09-11 09:58
![image](https://user-images.githubusercontent.com/38582754/64687809-c32e2700-d4bd-11e9-9af4-8f41d17935d7.png)

**Comment by lutzroeder** [comment] 2019-09-11 13:57
Duplicate of 322

**Closed by lutzroeder** 2019-09-11 13:57 UTC
Labels: duplicate
