### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ryusaeba** [lutzroeder/netron#589] opened 2020-09-02 03:33 UTC
- Netron app and version: 4.4.8 App and Browser
- OS and browser version: Windows 10 + Chrome Version 84.0.4147.135

Steps to Reproduce:

[EfficientDet-d0.zip](https://github.com/lutzroeder/netron/files/5159940/EfficientDet-d0.zip)

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment] 2020-09-29 02:46
[EfficientDet-d0.onnx.zip](https://github.com/lutzroeder/netron/files/5296050/EfficientDet-d0.onnx.zip)

**Comment by ck1070989** [comment] 2021-02-14 00:34
[netron_issue.tar.gz](https://github.com/lutzroeder/netron/files/5976788/netron_issue.tar.gz)

**Comment by Colombel-Vincent** [comment] 2021-02-23 10:22
I have the same problem on 4.7.9 on browser with this model [
[subword-conformer.zip](https://github.com/lutzroeder/netron/files/6028217/subword-conformer.zip)

](url)

**Comment by lutzroeder** [comment] 2021-02-24 02:28
[subword-conformer.zip](https://github.com/lutzroeder/netron/files/6032934/subword-conformer.zip)

**Comment by skottmckay** [comment] 2021-03-04 04:42
I see the same error with the mobilebert onnx model with the latest Netron release. Netron 3.6.5 is however able to open the model. .

**Comment by yyfcc17** [comment] 2021-03-05 07:09
https://github.com/lutzroeder/netron/issues/695 , feature requested

**Comment by lutzroeder** [comment] 2021-03-05 07:14
For context, folks that want to investigate and submit a fix. The error happens when the graph is too large for the graph layout algorithm in [dagre](https://github.com/dagrejs/dagre) to handle. It is not related to the file or weights size.

**Comment by linchpinlin** [comment] 2021-08-17 03:54
[issue_model.zip](https://github.com/lutzroeder/netron/files/6996951/last_hidden_state_crf_jud.zip)

**Comment by lutzroeder** [comment] 2021-09-12 03:02
[EfficientDet-d0.onnx.zip](https://github.com/lutzroeder/netron/files/5296050/EfficientDet-d0.onnx.zip)
[subword-conformer.latest.tflite.zip](https://github.com/lutzroeder/netron/files/7148911/subword-conformer.latest.tflite.zip)
[cnn.onnx.zip](https://github.com/lutzroeder/netron/files/7148909/cnn.onnx.zip)
[last_hidden_state_crf_jud.onnx.zip](https://github.com/lutzroeder/netron/files/7148912/last_hidden_state_crf_jud.onnx.zip)

**Comment by lutzroeder** [comment] 2021-09-12 07:13
Duplicate of #68

**Comment by luchangli03** [comment] 2022-01-21 01:02
Is it possible to set a larger Maximum call stack size?

**Comment by lutzroeder** [comment] 2022-01-21 02:31
@luchangli03 can you share a sample file to reproduce the issue.

**Comment by luchangli03** [comment] 2022-01-21 02:35
I have a vision transformer model that has 23359 nodes can't be opened by netron by this error, but I can't upload it.

**Comment by lutzroeder** [comment] 2022-01-21 02:37
@luchangli03 in this case you will need to investigate the issue and suggest a fix.

**Comment by Amur-Pal** [comment] 2022-07-14 15:13
Has a fix to this problem been found?

**Comment by lutzroeder** [comment] 2022-07-15 04:23
@Amur-Pal can you share a model file to reproduce the issue?

**Comment by Amur-Pal** [comment] 2022-07-15 07:20
File was too big for Github, here's a drive [link](https://drive.google.com/file/d/1K8JvY9SXtRyLHruXnKflbpKYNPANRv_-/view?usp=sharing).

**Comment by harry-stark** [comment] 2022-07-20 11:11
@lutzroeder This [file](https://huggingface.co/joeddav/xlm-roberta-large-xnli/blob/main/tf_model.h5) also produces the issue, I checked it with Netron==5.9.4.

**Closed** 2022-07-21 04:27 UTC
Labels: help wanted, no repro, bug

**Comment by Amur-Pal** [comment] 2022-07-21 14:20
The error has disappeared but now nothing shows up after a long time of waiting...
