### ISSUE TITLE
Feature to export model in different format

### ISSUE THREAD

**Issue by vikramdattu** [lutzroeder/netron#495] opened 2020-05-19 05:16 UTC
Hi @lutzroeder 

Is it possible to add a feature to export an imported model to different format?
Is it okay if that feature only desktop specific.

I am looking for a tool to import a .tflite model and optimize it for size with obvious tradeoffs in accuracy.

**Comment by lutzroeder** [comment] 2020-05-19 05:33
Duplicate of #415

**Closed by lutzroeder** 2020-05-19 05:33 UTC
