### ISSUE TITLE
PyPI: old releases are being deleted

### ISSUE THREAD

**Issue by somewacko** [lutzroeder/netron#604] opened 2020-09-23 22:35 UTC
It appears that old versions of this package are being deleted from PyPI. We have a server build which uses netron as a dependency but it will occasionally break because the version of netron that we pinned no longer exists.

Is there a reason that old versions are being deleted? We've been using this tool to visualize TFLite and the Python module is convenient.

Thanks!

**Comment by lutzroeder** [comment] 2020-09-25 01:05
The goal is to eliminate suppport cost for outdated versions and maximize users participating in stabilizing the latest version.

**Comment by topshik** [comment] 2023-01-18 12:22
Users have other work to do besides supporting every one of tens dependencies that they use in the project. Updating dependencies every month makes users of the package feel unnecessary pain rather than will to support.

**Comment by xich** [comment] 2024-09-18 17:57
Please stop deleting old versions.

You don't have to support them or do bug fixes, etc, but breaking every build in the world and forcing an upgrade once a month is creating an incredible amount of work for your users and makes it impossible to build old versions of our own code.

At the point where I'm campaigning to not use the package at all.

**Comment by lutzroeder** [comment] 2024-09-25 01:08
Duplicate of #1366

**Closed by lutzroeder** 2024-09-25 01:08 UTC
Labels: bug

**Comment by IljaManakov** [comment] 2024-10-18 20:13
For anyone else being burned by this issue: The sky-high number of forks is probably not a coincidence.

The best solution we found is to also fork the repo and use direct references (@) in our requirements to point directly to a commit in the fork.

Hope this helps someone else to avoid facing randomly breaking tests every month.
