### ISSUE TITLE
CoreML: block_specializations.CoreML7

### ISSUE THREAD

**Issue by aseemw** [lutzroeder/netron#1149] opened 2023-09-10 04:52 UTC
- Netron app and version: 7.1.6
- OS and browser version: macOS Ventura 

**Error: "Cannot read properties of undefined (reading 'operations')"** 

Steps to Reproduce:

Model attached. Here is the code that produced it 

```
# coremltools==7.0b2

import coremltools as ct
import coremltools.optimize.torch as cto
import torch
import torch.nn as nn

torch_model = nn.Sequential(
                        nn.Conv2d(3, 12, (1, 1), (1, 1), padding=(0, 0)),
                        nn.BatchNorm2d(12),
              )

data = torch.randn(1, 3, 32, 32)
config = cto.quantization.LinearQuantizerConfig.from_dict(
    {
        "global_config": {
            "quantization_scheme": "symmetric",
            "weight_per_channel": True,
        }
    }
)

quantizer = cto.quantization.LinearQuantizer(torch_model, config)
prepared_model = quantizer.prepare(example_inputs=data, inplace=False)
prepared_model(data)
finalized_model = quantizer.finalize(inplace=False)

traced_model = torch.jit.trace(finalized_model, example_inputs=data)

mlmodel = ct.convert(
        traced_model,
        inputs=[ct.TensorType(shape=data.shape)],
        minimum_deployment_target=ct.target.iOS17,
    )
mlmodel.save("simple_activation_quantized_model.mlpackage")
```

<img width="326" alt="err" src="https://github.com/lutzroeder/netron/assets/7546478/e672ae2a-bef0-4e15-b46a-6151f5c6e7e7">

[simple_activation_quantized_model.mlpackage.zip](https://github.com/lutzroeder/netron/files/12567518/simple_activation_quantized_model.mlpackage.zip)

**Comment by lutzroeder** [comment] 2023-09-10 16:42
@aseemw please submit a pull requests with proposed fixes for Core ML issues.

**Comment by lutzroeder** [comment] 2023-09-10 16:45
Duplicate of #193

**Closed by lutzroeder** 2023-09-10 16:45 UTC
Labels: bug

**Comment by aseemw** [comment] 2023-09-10 18:39
@lutzroeder 
sorry I do not fully follow. You made this issue a duplicate of #193, but that one is also closed. Shouldn't there be an open issue to track this?  Are all the issues in #193 due to the same root cause, hence you have clubbed them together? 

> @aseemw please submit pull requests with proposed fixes for Core ML issues.

I am not sure which part of the code is failing with this model. I can definitely help to clarify on how to parse the proto messages, if a specific message is tripping the parsing code. Do you know which exact proto message is leading to this error of "cannot read properties of undefined"?
