### ISSUE TITLE
TF Saved model shows only one node - StatefulPartitionedCall

### ISSUE THREAD

**Issue by apivovarov** [lutzroeder/netron#761] opened 2021-07-01 17:00 UTC
I created basic TF image classification model as described [in the tutorial](https://www.tensorflow.org/tutorials/keras/classification) (using tensorflow==2.5.0)
I saved the model.
There is `saved_model.pb` file Inside the saved model directory (which should contain the model graph).
When I open it in Netron I see just single super-node `StatefulPartitionedCall` with bunch on inputs.
- How to see the actual graph?
- Is it possible in general? 
- Can I "trace" saved model with some test input and save the graph?

Script to create and save test TF model:
```
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])


class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
train_images = train_images / 255.0
test_images = test_images / 255.0
model.fit(train_images, train_labels, epochs=10)

model.save("mymodel")
```

**Comment by lutzroeder** [comment] 2021-07-01 17:39
Duplicate of #342

**Closed by lutzroeder** 2021-07-01 17:39 UTC
Labels: feature

**Comment by lutzroeder** [comment] 2021-07-02 03:31
[netron_issue_761.zip](https://github.com/lutzroeder/netron/files/6751899/netron_issue_761.zip)
